### ISSUE TITLE
prev not initialized

### ISSUE THREAD

**Issue by BrandonSpitler** [busunkim96/Kim_CSCI2270_FinalProject#1]
prev wasn't initialized when I ran at which might work on code blocks but not visual studios I initialized it just take a look at my fork request and see if it looks good make sure I didn't change anything important in your code

**Comment by busunkim96** [comment]
Thanks for letting me know. Do you want to do a pull request?

**Comment by BrandonSpitler** [comment]
Oh yeah sorry I just forked it here I pulled requested. I also pull requested another one however the ease of that change is making me uneasy
